import { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import './navigation.css'
const api=import.meta.env.VITE_API_URL??'http://localhost:5178/api'; const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}); const labels={Quoted:'Orçamento',Approved:'Aprovado',InProduction:'Produção',Ready:'Pronto',Delivered:'Entregue',Cancelled:'Cancelado'};
async function call(path,options={}){const r=await fetch(`${api}${path}`,{headers:{'Content-Type':'application/json'},...options});if(!r.ok)throw new Error('Não foi possível concluir a operação.');return r.status===204?null:r.json()}
function Metric({label,value,hint}){return <article className="metric"><span>{label}</span><strong>{value}</strong>{hint&&<small>{hint}</small>}</article>}
function App(){const [page,setPage]=useState('Visão geral'),[data,setData]=useState({clients:[],catalog:[],orders:[],dashboard:null}),[error,setError]=useState(''),[notice,setNotice]=useState('');const [client,setClient]=useState({name:'',phone:'',email:'',cpf:'',notes:'',address:null}),[editingClientId,setEditingClientId]=useState(null);const [item,setItem]=useState({kind:'Service',name:'',description:'',basePrice:'',estimatedDays:'3',service:{unit:'peça',instructions:''},garment:null});
const load=async()=>{try{setError('');const [clients,catalog,orders,dashboard]=await Promise.all(['/clients','/catalog','/orders','/dashboard'].map(call));setData({clients,catalog,orders,dashboard})}catch(e){setError(e.message)}};useEffect(()=>{load()},[]);const act=async(fn,msg)=>{try{await fn();setNotice(msg);await load()}catch(e){setError(e.message)}};
const addClient=e=>{e.preventDefault();const isEditing=Boolean(editingClientId);act(()=>call(isEditing?/clients/:'/clients',{method:isEditing?'PUT':'POST',body:JSON.stringify(client)}),isEditing?'Cliente atualizado.':'Cliente incluído.');setClient({name:'',phone:'',email:'',cpf:'',notes:'',address:null});setEditingClientId(null)};const addItem=e=>{e.preventDefault();const payload={...item,basePrice:Number(item.basePrice),estimatedDays:Number(item.estimatedDays),service:item.kind==='Service'?item.service:null,garment:item.kind==='Garment'?{garmentType:item.garment?.garmentType||'',requiredMeasurements:item.garment?.requiredMeasurements||'',productionStages:'',materials:''}:null};act(()=>call('/catalog',{method:'POST',body:JSON.stringify(payload)}),'Item incluído.');setItem({kind:'Service',name:'',description:'',basePrice:'',estimatedDays:'3',service:{unit:'peça',instructions:''},garment:null})};
return <main><aside><p className="brand">Linha & Laço</p><h1>Back-office</h1><nav aria-label="Seções">{['Visão geral','Clientes','Catálogo','Pedidos'].map(x=><button key={x} className={page===x?'active':''} onClick={()=>setPage(x)}>{x}</button>)}</nav></aside><section className="content"><header><div><p className="eyebrow">Gestão do ateliê</p><h2>{page}</h2></div><button onClick={load}>Atualizar dados</button></header>{error&&<p className="error">{error}</p>}{notice&&<p className="notice">{notice}</p>}
{page==='Visão geral'&&data.dashboard&&<><section className="metrics"><Metric label="Recebido" value={money.format(data.dashboard.received)}/><Metric label="Previsto" value={money.format(data.dashboard.expected)}/><Metric label="Em atraso" value={money.format(data.dashboard.overdue)}/><Metric label="Ticket médio" value={money.format(data.dashboard.averageTicket)}/></section><section className="panels"><article><p className="eyebrow">Pipeline</p><h3>Pedidos por etapa</h3><div className="rows">{Object.entries(data.dashboard.ordersByStatus).map(([key,count])=><div key={key}><span>{labels[key]||key}</span><b>{count}</b></div>)}</div></article><article><p className="eyebrow">Itens em destaque</p><h3>Mais vendidos</h3><div className="rows">{data.dashboard.bestSellers.map(x=><div key={x.name}><span>{x.name}</span><b>{x.quantity} un.</b></div>)}</div></article></section><footer><span>{data.dashboard.orders} pedidos no período · {data.dashboard.activeClients} clientes ativos</span><b>{data.dashboard.quoteConversion}% de conversão</b></footer></>}
{page==='Clientes'&&<section className="panels"><article><h3>Cadastrar cliente</h3><form onSubmit={addClient}><input required placeholder="Nome" value={client.name} onChange={e=>setClient({...client,name:e.target.value})}/><input placeholder="Telefone" value={client.phone} onChange={e=>setClient({...client,phone:e.target.value})}/><input type="email" placeholder="E-mail" value={client.email} onChange={e=>setClient({...client,email:e.target.value})}/><button>Adicionar cliente</button></form></article><article><h3>Clientes cadastrados</h3><div className="rows">{data.clients.map(x=><div key={x.id}><span><b>{x.name}</b><small>{x.phone||x.email||'Sem contato'}</small></span><button className="secondary" onClick={()=>{setClient(x);setEditingClientId(x.id)}}>Carregar para edição</button></div>)}</div></article></section>}
{page==='Catálogo'&&<section className="panels"><article><h3>Novo item</h3><form onSubmit={addItem}><select value={item.kind} onChange={e=>setItem({...item,kind:e.target.value,service:e.target.value==='Service'?{unit:'peça',instructions:''}:null,garment:e.target.value==='Garment'?{}:null})}><option value="Service">Serviço</option><option value="Garment">Confecção</option></select><input required placeholder="Nome" value={item.name} onChange={e=>setItem({...item,name:e.target.value})}/><input required type="number" min="0" step="0.01" placeholder="Preço" value={item.basePrice} onChange={e=>setItem({...item,basePrice:e.target.value})}/><input required type="number" min="0" placeholder="Prazo em dias" value={item.estimatedDays} onChange={e=>setItem({...item,estimatedDays:e.target.value})}/>{item.kind==='Garment'&&<input required placeholder="Tipo de peça" value={item.garment?.garmentType||''} onChange={e=>setItem({...item,garment:{...item.garment,garmentType:e.target.value}})}/>}<button>Adicionar ao catálogo</button></form></article><article><h3>Catálogo operacional</h3><div className="rows">{data.catalog.map(x=><div key={x.id}><span><b>{x.name}</b><small>{x.kind==='Service'?'Serviço':'Confecção'} · {money.format(x.basePrice)} · {x.active?'Ativo':'Inativo'}</small></span><button className="secondary" onClick={()=>act(()=>call(`/catalog/${x.id}/active`,{method:'PATCH',body:JSON.stringify({active:!x.active})}),x.active?'Item desativado.':'Item ativado.')}>{x.active?'Desativar':'Ativar'}</button></div>)}</div></article></section>}
{page==='Pedidos'&&<section className="panels"><article className="wide"><h3>Pedidos e cobrança</h3><div className="rows">{data.orders.map(order=><div key={order.id}><span><b>{order.number} · {data.clients.find(x=>x.id===order.clientId)?.name||'Cliente'}</b><small>{order.items.map(x=>x.nameSnapshot).join(', ')} · {money.format(order.total)} · {labels[order.status]}</small></span><span className="actions">{order.status!=='Delivered'&&order.status!=='Cancelled'&&<button className="secondary" onClick={()=>{const next={Quoted:'Approved',Approved:'InProduction',InProduction:'Ready',Ready:'Delivered'}[order.status];act(()=>call(`/orders/${order.id}/status`,{method:'PATCH',body:JSON.stringify({status:next})}),'Pedido avançou no pipeline.')}}>Avançar</button>}{order.installments.filter(x=>x.status!=='Paid').map(x=><button className="secondary" key={x.id} onClick={()=>act(()=>call(`/installments/${x.id}/pay`,{method:'POST'}),'Pagamento confirmado.')}>Receber {money.format(x.amount)}</button>)}<a className="button-link" href={`${api}/orders/${order.id}/receipt`} target="_blank">Recibo</a></span></div>)}</div></article></section>}
</section></main>}
createRoot(document.getElementById('root')).render(<App />)