import { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'
import './notes.css'

const api = import.meta.env.VITE_API_URL ?? 'http://localhost:5178/api'
const money = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' })
const labels = { Quoted:'Orçamento', Approved:'Aprovado', InProduction:'Em produção', Ready:'Pronto', Delivered:'Entregue', Cancelled:'Cancelado' }
const emptyClient = { name:'', phone:'', email:'', cpf:'', notes:'', address:null }
const emptyCatalog = { kind:'Service', name:'', description:'', basePrice:'', estimatedDays:'3', service:{ unit:'peça', instructions:'' }, garment:null }

async function request(path, options = {}) { const response = await fetch(`${api}${path}`, { headers:{ 'Content-Type':'application/json', ...(options.headers||{}) }, ...options }); if (!response.ok) { let message='Não foi possível concluir a ação.'; try { const body=await response.json(); message=Object.values(body.errors||{}).flat().join(' ')||message } catch {} throw new Error(message) } return response.status === 204 ? null : response.json() }
function Field({label, ...props}) { return <label className="field"><span>{label}</span><input {...props}/></label> }
function App() {
  const [page,setPage]=useState('início'), [data,setData]=useState({clients:[],catalog:[],orders:[],notes:[],dashboard:null}), [error,setError]=useState(''), [notice,setNotice]=useState('')
  const [client,setClient]=useState(emptyClient), [editingClientId,setEditingClientId]=useState(null), [catalog,setCatalog]=useState(emptyCatalog), [order,setOrder]=useState({clientId:'', catalogItemId:'', quantity:1, promisedFor:'', amount:'', dueDate:'', notes:''}), [note,setNote]=useState('')
  const load=async()=>{ try { setError(''); const [clients,catalog,orders,notes,dashboard]=await Promise.all(['/clients','/catalog','/orders','/notes','/dashboard'].map(path=>request(path))); setData({clients,catalog,orders,notes,dashboard}) } catch(e){setError(e.message)} }
  useEffect(()=>{load()},[])
  const action=async(work, success)=>{try{setError(''); await work(); setNotice(success); await load()}catch(e){setError(e.message)}}
  const activeCatalog=useMemo(()=>data.catalog.filter(item=>item.active),[data.catalog])
  const saveClient=e=>{e.preventDefault(); const isEditing=Boolean(editingClientId); action(()=>request(isEditing ? /clients/ : '/clients',{method:isEditing?'PUT':'POST',body:JSON.stringify({...client,address:null})}),isEditing?'Cliente atualizado.':'Cliente cadastrado.'); setClient(emptyClient); setEditingClientId(null)}
  const saveCatalog=e=>{e.preventDefault(); const body={...catalog,basePrice:Number(catalog.basePrice),estimatedDays:Number(catalog.estimatedDays),service:catalog.kind==='Service'?catalog.service:null,garment:catalog.kind==='Garment'?{garmentType:catalog.garment?.garmentType||'',requiredMeasurements:catalog.garment?.requiredMeasurements||'',productionStages:catalog.garment?.productionStages||'',materials:catalog.garment?.materials||''}:null}; action(()=>request('/catalog',{method:'POST',body:JSON.stringify(body)}),'Item salvo no catálogo.'); setCatalog(emptyCatalog)}
  const saveOrder=e=>{e.preventDefault(); const item=activeCatalog.find(x=>x.id===order.catalogItemId); if(!item) return setError('Escolha um item ativo.'); const total=Number(order.amount)||item.basePrice*Number(order.quantity); const installments=order.dueDate?[{amount:total,dueDate:order.dueDate}]:[]; action(()=>request('/orders',{method:'POST',body:JSON.stringify({clientId:order.clientId,promisedFor:order.promisedFor||null,notes:order.notes,items:[{catalogItemId:item.id,quantity:Number(order.quantity),unitPrice:item.basePrice}],installments})}),'Pedido criado.'); setOrder({clientId:'',catalogItemId:'',quantity:1,promisedFor:'',amount:'',dueDate:'',notes:''})}
  return <main><header><div><p className="eyebrow">Linha & Laço</p><h1>Ateliê em movimento.</h1></div><button onClick={load}>Atualizar</button></header><nav className="tabs">{['início','clientes','catálogo','pedidos'].map(item=><button key={item} className={page===item?'active':''} onClick={()=>setPage(item)}>{item}</button>)}</nav>{error&&<p className="error">{error}</p>}{notice&&<p className="notice">{notice}</p>}
  {page==='início'&&<><section className="summary"><article><strong>{data.clients.length}</strong><span>clientes</span></article><article><strong>{data.orders.filter(x=>!['Delivered','Cancelled'].includes(x.status)).length}</strong><span>pedidos ativos</span></article><article><strong>{money.format(data.dashboard?.expected||0)}</strong><span>vendas no período</span></article></section><section className="grid"><article className="card"><p className="eyebrow">Novo cliente</p><h2>Comece pelo cuidado.</h2><form onSubmit={saveClient}><Field label="Nome completo" required value={client.name} onChange={e=>setClient({...client,name:e.target.value})}/><Field label="Telefone" value={client.phone} onChange={e=>setClient({...client,phone:e.target.value})}/><button>Cadastrar cliente</button></form></article><article className="card"><p className="eyebrow">Pedidos</p><h2>Próximos trabalhos</h2><div className="list">{data.orders.slice(0,5).map(order=><OrderRow key={order.id} order={order} clients={data.clients} action={action}/>)}</div></article></section><Notes notes={data.notes} note={note} setNote={setNote} action={action}/></>}
  {page==='clientes'&&<section className="grid"><article className="card"><h2>Novo cliente</h2><form onSubmit={saveClient}><Field label="Nome" required value={client.name} onChange={e=>setClient({...client,name:e.target.value})}/><Field label="Telefone" value={client.phone} onChange={e=>setClient({...client,phone:e.target.value})}/><Field label="E-mail" type="email" value={client.email} onChange={e=>setClient({...client,email:e.target.value})}/><Field label="CPF" value={client.cpf} onChange={e=>setClient({...client,cpf:e.target.value})}/><label className="field"><span>Observações</span><textarea value={client.notes} onChange={e=>setClient({...client,notes:e.target.value})}/></label><button>Salvar cliente</button></form></article><article className="card"><h2>Base de clientes</h2><div className="list">{data.clients.map(item=><div key={item.id}><span><b>{item.name}</b><small>{item.phone||item.email||'Sem contato'}</small></span><button type="button" className="secondary" onClick={()=>{setClient(item);setEditingClientId(item.id)}}>Editar no formulário</button></div>)}</div></article></section>}
  {page==='catálogo'&&<section className="grid"><article className="card"><h2>Novo produto ou serviço</h2><form onSubmit={saveCatalog}><label className="field"><span>Tipo</span><select value={catalog.kind} onChange={e=>setCatalog({...catalog,kind:e.target.value,service:e.target.value==='Service'?{unit:'peça',instructions:''}:null,garment:e.target.value==='Garment'?{}:null})}><option value="Service">Serviço</option><option value="Garment">Confecção</option></select></label><Field label="Nome" required value={catalog.name} onChange={e=>setCatalog({...catalog,name:e.target.value})}/><Field label="Preço base" type="number" min="0" step="0.01" required value={catalog.basePrice} onChange={e=>setCatalog({...catalog,basePrice:e.target.value})}/><Field label="Prazo estimado (dias)" type="number" min="0" required value={catalog.estimatedDays} onChange={e=>setCatalog({...catalog,estimatedDays:e.target.value})}/><label className="field"><span>Descrição</span><textarea value={catalog.description} onChange={e=>setCatalog({...catalog,description:e.target.value})}/></label>{catalog.kind==='Service'?<Field label="Instruções do serviço" value={catalog.service?.instructions||''} onChange={e=>setCatalog({...catalog,service:{...catalog.service,instructions:e.target.value}})}/>:<><Field label="Tipo de peça" required value={catalog.garment?.garmentType||''} onChange={e=>setCatalog({...catalog,garment:{...catalog.garment,garmentType:e.target.value}})}/><Field label="Medidas necessárias" value={catalog.garment?.requiredMeasurements||''} onChange={e=>setCatalog({...catalog,garment:{...catalog.garment,requiredMeasurements:e.target.value}})}/></>}<button>Salvar item</button></form></article><article className="card"><h2>Catálogo</h2><div className="list">{data.catalog.map(item=><div key={item.id}><span><b>{item.name}</b><small>{item.kind==='Service'?'Serviço':'Confecção'} · {money.format(item.basePrice)} · {item.estimatedDays} dias</small></span><button className="secondary" onClick={()=>action(()=>request(`/catalog/${item.id}/active`,{method:'PATCH',body:JSON.stringify({active:!item.active})}),item.active?'Item desativado.':'Item ativado.')}>{item.active?'Desativar':'Ativar'}</button></div>)}</div></article></section>}
  {page==='pedidos'&&<section className="grid"><article className="card"><h2>Novo pedido</h2><form onSubmit={saveOrder}><label className="field"><span>Cliente</span><select required value={order.clientId} onChange={e=>setOrder({...order,clientId:e.target.value})}><option value="">Selecione</option>{data.clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label className="field"><span>Item</span><select required value={order.catalogItemId} onChange={e=>setOrder({...order,catalogItemId:e.target.value})}><option value="">Selecione</option>{activeCatalog.map(i=><option key={i.id} value={i.id}>{i.name} — {money.format(i.basePrice)}</option>)}</select></label><Field label="Quantidade" type="number" min="1" required value={order.quantity} onChange={e=>setOrder({...order,quantity:e.target.value})}/><Field label="Entrega prometida" type="date" value={order.promisedFor} onChange={e=>setOrder({...order,promisedFor:e.target.value})}/><Field label="Vencimento da parcela" type="date" value={order.dueDate} onChange={e=>setOrder({...order,dueDate:e.target.value})}/><label className="field"><span>Observações</span><textarea value={order.notes} onChange={e=>setOrder({...order,notes:e.target.value})}/></label><button>Criar pedido</button></form></article><article className="card"><h2>Todos os pedidos</h2><div className="list">{data.orders.map(item=><OrderRow key={item.id} order={item} clients={data.clients} action={action}/>)}</div></article></section>}
  </main>
}
function OrderRow({order,clients,action}) { const next={Quoted:'Approved',Approved:'InProduction',InProduction:'Ready',Ready:'Delivered'}[order.status]; return <div><span><b>{order.number} · {clients.find(c=>c.id===order.clientId)?.name||'Cliente'}</b><small>{order.items.map(x=>x.nameSnapshot).join(', ')} · {money.format(order.total)}</small><small>{labels[order.status]}</small></span><span className="row-actions">{next&&<button className="secondary" onClick={()=>action(()=>request(`/orders/${order.id}/status`,{method:'PATCH',body:JSON.stringify({status:next})}),'Status do pedido atualizado.')}>Avançar</button>}{order.installments?.filter(x=>x.status!=='Paid').map(p=><button key={p.id} className="secondary" onClick={()=>action(()=>request(`/installments/${p.id}/pay`,{method:'POST'}),'Pagamento confirmado.')}>Receber {money.format(p.amount)}</button>)}<a className="button-link" href={`${api}/orders/${order.id}/receipt`} target="_blank">Recibo</a></span></div> }
function Notes({notes,note,setNote,action}) { return <section className="card notes-card"><p className="eyebrow">Anotações</p><h2>Não deixe um pedido escapar.</h2><form className="note-form" onSubmit={e=>{e.preventDefault(); action(()=>request('/notes',{method:'POST',body:JSON.stringify({text:note})}),'Anotação salva.'); setNote('')}}><input required placeholder="Ex.: ligar para cliente sobre prova" value={note} onChange={e=>setNote(e.target.value)}/><button>Salvar anotação</button></form><div className="notes">{notes.map(item=><div className={item.isDone?'note done':'note'} key={item.id}><label><input type="checkbox" checked={item.isDone} onChange={()=>action(()=>request(`/notes/${item.id}`,{method:'PATCH',body:JSON.stringify({isDone:!item.isDone})}),'Anotação atualizada.')}/><span>{item.text}</span></label><button className="secondary" onClick={()=>action(()=>request(`/notes/${item.id}`,{method:'DELETE'}),'Anotação removida.')}>Excluir</button></div>)}</div></section> }
createRoot(document.getElementById('root')).render(<App />)